use_frameworks!

platform :ios, '10.0'

target 'SafeNotifyManager_Example' do
  pod 'SafeNotifyManager', :path => '../'

  target 'SafeNotifyManager_Tests' do
    inherit! :search_paths

    
  end
end
